export const PRODUCTS_REQUESTED = "PRODUCTS_REQUESTED"
export const PRODUCTS_LOADED = "PRODUCTS_LOADED" 
export const PRODUCTS_ERROR = "PRODUCTS_ERROR"

export const PRODUCT_ADDED_TO_CART = "PRODUCT_ADDED_TO_CART"
export const PRODUCT_REMOVED_FROM_CART = "PRODUCT_REMOVED_FROM_CART"
export const PRODUCTS_REMOVED_FROM_CART = "PRODUCTS_REMOVED_FROM_CART"